// ui/admin/src/views/Dashboard.vue
<template>
  <div v-if="!hasStatus">
    <PageHeader
      icon="mdi-home"
      title="System Overview"
      overline="Admin Dashboard"
      description="Monitor and manage your ShellHub instance metrics and statistics."
      icon-color="primary"
    />

    <v-row class="d-flex align-center mb-2 pa-3">
      <v-icon
        class="mr-2"
        icon="mdi-chart-box-outline"
      />
      <h2 class="text-h6">
        Stats
      </h2>
    </v-row>
    <v-row>
      <v-col
        cols="12"
        md="4"
      >
        <StatCard
          title="Registered Users"
          :stat="stats.registered_users ?? 0"
          icon="mdi-account-group"
          button-label="View all Users"
          path="users"
        />
      </v-col>

      <v-col
        cols="12"
        md="4"
      >
        <StatCard
          title="Registered Devices"
          :stat="stats.registered_devices ?? 0"
          icon="mdi-developer-board"
          button-label="View all Devices"
          path="devices"
        />
      </v-col>

      <v-col
        cols="12"
        md="4"
      >
        <StatCard
          title="Online Devices"
          :stat="stats.online_devices ?? 0"
          icon="mdi-lan-connect"
          button-label="View Online Devices"
          path="devices"
        />
      </v-col>

      <v-col
        cols="12"
        md="4"
      >
        <StatCard
          title="Pending Devices"
          :stat="stats.pending_devices ?? 0"
          icon="mdi-clock-outline"
          button-label="View Pending Devices"
          path="devices"
        />
      </v-col>

      <v-col
        cols="12"
        md="4"
      >
        <StatCard
          title="Rejected Devices"
          :stat="stats.rejected_devices ?? 0"
          icon="mdi-close-circle"
          button-label="View Rejected Devices"
          path="devices"
        />
      </v-col>

      <v-col
        cols="12"
        md="4"
      >
        <StatCard
          title="Active Sessions"
          :stat="stats.active_sessions ?? 0"
          icon="mdi-history"
          button-label="View all Sessions"
          path="sessions"
        />
      </v-col>
    </v-row>
  </div>

  <v-card
    v-else
    data-test="dashboard-failed"
    class="mt-2 pa-4 bg-v-theme-surface"
  >
    <p class="text-center">
      Something is wrong, try again!
    </p>
  </v-card>
</template>

<script setup lang="ts">
import axios, { AxiosError } from "axios";
import { onMounted, ref } from "vue";
import useStatsStore from "@admin/store/modules/stats";
import { IAdminStats } from "@admin/interfaces/IStats";
import useSnackbar from "@/helpers/snackbar";
import StatCard from "@/components/StatCard.vue";
import PageHeader from "@/components/PageHeader.vue";

const snackbar = useSnackbar();
const statsStore = useStatsStore();
const hasStatus = ref(false);
const stats = ref({} as IAdminStats);

onMounted(async () => {
  try {
    stats.value = await statsStore.getStats();
  } catch (error: unknown) {
    hasStatus.value = true;
    if (axios.isAxiosError(error)) {
      const axiosError = error as AxiosError;
      if (axiosError.response?.status === 402) {
        snackbar.showError("Failed to load the dashboard stats. Check your license and try again.");
      } else {
        snackbar.showError("Failed to load the dashboard stats. Please try again.");
      }
    }
  }
});

defineExpose({ stats, hasStatus });
</script>

// ui/apps/console/src/pages/admin/Dashboard.tsx
import type { ReactNode } from "react";
import {
  UsersIcon,
  CpuChipIcon,
  SignalIcon,
  ClockIcon,
  XCircleIcon,
  CommandLineIcon,
  ChartBarIcon,
  ExclamationCircleIcon,
} from "@heroicons/react/24/outline";
import PageHeader from "@/components/common/PageHeader";
import StatCard from "@/components/common/StatCard";
import RecentSessionsTable from "@/components/sessions/RecentSessionsTable";
import { useAdminStats } from "@/hooks/useAdminStats";
import PageLoader from "@/components/common/PageLoader";

export default function AdminDashboard() {
  const {
    stats: statsData,
    isLoading: statsLoading,
    isError: statsError,
  } = useAdminStats();

  if (statsLoading) {
    return <PageLoader label="Loading dashboard statistics" padding="fill" />;
  }

  if (statsError) {
    return (
      <div className="h-full flex items-center justify-center">
        <div className="text-center" role="alert">
          <ExclamationCircleIcon className="w-10 h-10 text-accent-red mx-auto mb-3" />
          <p className="text-sm font-medium text-text-primary">
            Failed to load dashboard statistics
          </p>
          <p className="text-2xs text-text-muted mt-1">
            Please try again later.
          </p>
        </div>
      </div>
    );
  }

  const stats = statsData ?? {};

  const statCards: Array<{
    value: number;
    icon: ReactNode;
    title: string;
    linkLabel: string;
    linkTo: string;
    accent?: string;
  }> = [
    {
      value: stats.registered_users ?? 0,
      icon: <UsersIcon className="w-7 h-7" />,
      title: "Registered Users",
      linkLabel: "View all Users",
      linkTo: "/admin/users",
    },
    {
      value: stats.registered_devices ?? 0,
      icon: <CpuChipIcon className="w-7 h-7" />,
      title: "Registered Devices",
      linkLabel: "View all Devices",
      linkTo: "/admin/devices",
    },
    {
      value: stats.online_devices ?? 0,
      icon: <SignalIcon className="w-7 h-7" />,
      title: "Online Devices",
      linkLabel: "View Online Devices",
      linkTo: "/admin/devices",
      accent: "text-accent-green",
    },
    {
      value: stats.pending_devices ?? 0,
      icon: <ClockIcon className="w-7 h-7" />,
      title: "Pending Devices",
      linkLabel: "View Pending Devices",
      linkTo: "/admin/devices",
      accent: "text-accent-yellow",
    },
    {
      value: stats.rejected_devices ?? 0,
      icon: <XCircleIcon className="w-7 h-7" />,
      title: "Rejected Devices",
      linkLabel: "View Rejected Devices",
      linkTo: "/admin/devices",
      accent: "text-accent-red",
    },
    {
      value: stats.active_sessions ?? 0,
      icon: <CommandLineIcon className="w-7 h-7" />,
      title: "Active Sessions",
      linkLabel: "View all Sessions",
      linkTo: "/admin/sessions",
    },
  ];

  return (
    <div>
      <PageHeader
        icon={<ChartBarIcon className="w-6 h-6" />}
        overline="Admin Dashboard"
        title="System Overview"
        description="Monitor key metrics about users, devices, and sessions across the instance."
      />

      <div className="mb-4">
        <p className="text-2xs font-mono font-semibold uppercase tracking-label text-text-muted mb-4">
          Stats
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-10">
        {statCards.map((card, i) => (
          <div
            key={card.title}
            className="animate-slide-up"
            style={{ animationDelay: `${i * 80}ms` }}
          >
            <StatCard
              icon={card.icon}
              title={card.title}
              value={card.value}
              linkLabel={card.linkLabel}
              linkTo={card.linkTo}
              accent={card.accent}
            />
          </div>
        ))}
      </div>

      <RecentSessionsTable isAdmin />
    </div>
  );
}
