// ui/admin/src/views/SessionDetails.vue
<template>
  <h1>Session Details</h1>
  <v-card
    v-if="session?.uid"
    class="mt-2 border rounded bg-background"
  >
    <v-card-title class="pa-4 d-flex align-center justify-space-between bg-v-theme-surface">
      <div class="d-flex align-center ml-2 ga-3">
        <v-tooltip
          location="bottom"
          :text="session.active ? 'Active' : 'Inactive'"
        >
          <template #activator="{ props }">
            <v-icon
              v-bind="props"
              :color="session.active ? 'success' : 'white'"
              data-test="active-icon"
              icon="mdi-check-circle"
            />
          </template>
        </v-tooltip>
        <h2 class="text-h6">{{ session.uid }}</h2>
      </div>
    </v-card-title>

    <v-divider />

    <v-card-text class="pa-4 pt-0">
      <v-row class="py-3">
        <v-col
          cols="12"
          md="6"
          class="my-0 py-0"
        >
          <div data-test="session-uid-field">
            <h3 class="item-title">UID:</h3>
            <p class="text-truncate">{{ session.uid }}</p>
          </div>

          <div
            v-if="session.device"
            data-test="session-device-field"
          >
            <h3 class="item-title">Device:</h3>
            <router-link
              :to="{ name: 'deviceDetails', params: { id: session.device.uid } }"
              class="hyper-link"
            >
              {{ session.device.name || session.device.uid }}
            </router-link>
          </div>

          <div data-test="session-username-field">
            <h3 class="item-title">Username:</h3>
            <p>{{ session.username }}</p>
          </div>

          <div data-test="session-ip-field">
            <h3 class="item-title">IP Address:</h3>
            <code>{{ session.ip_address }}</code>
          </div>

          <div data-test="session-type-field">
            <h3 class="item-title">Type:</h3>
            <p class="text-capitalize">{{ session.type }}</p>
          </div>

          <div data-test="session-terminal-field">
            <h3 class="item-title">Terminal:</h3>
            <p>{{ session.term === "none" ? "-" : session.term }}</p>
          </div>
        </v-col>

        <v-col
          cols="12"
          md="6"
          class="my-0 py-0"
        >
          <div data-test="session-namespace-field">
            <h3 class="item-title">Namespace:</h3>
            <router-link
              :to="{ name: 'namespaceDetails', params: { id: session.tenant_id } }"
              class="hyper-link"
            >
              {{ session.device.namespace }}
            </router-link>
          </div>

          <div data-test="session-authenticated-field">
            <h3 class="item-title">Authenticated:</h3>
            <p>{{ session.authenticated ? 'Yes' : 'No' }}</p>
          </div>

          <div data-test="session-recorded-field">
            <h3 class="item-title">Recorded:</h3>
            <p>{{ session.recorded ? 'Yes' : 'No' }}</p>
          </div>

          <div data-test="session-started-field">
            <h3 class="item-title">Started At:</h3>
            <p>{{ formatFullDateTime(session.started_at) }}</p>
          </div>

          <div data-test="session-last-seen-field">
            <h3 class="item-title">Last Seen:</h3>
            <p>{{ formatFullDateTime(session.last_seen) }}</p>
          </div>
        </v-col>
      </v-row>
    </v-card-text>
  </v-card>
  <v-card
    v-else
    class="mt-2 pa-4 bg-v-theme-surface"
  >
    <p class="text-center">Something is wrong, try again!</p>
  </v-card>
</template>

<script setup lang="ts">
import { computed, onMounted } from "vue";
import { useRoute } from "vue-router";
import useSessionsStore from "@admin/store/modules/sessions";
import useSnackbar from "@/helpers/snackbar";
import { formatFullDateTime } from "@/utils/date";

const route = useRoute();
const snackbar = useSnackbar();
const sessionsStore = useSessionsStore();
const sessionId = computed(() => route.params.id);
const session = computed(() => sessionsStore.session);

onMounted(async () => {
  try {
    await sessionsStore.fetchSessionById(sessionId.value as string);
  } catch {
    snackbar.showError("Failed to get session details.");
  }
});
</script>

<style scoped>
.hyper-link {
  color: inherit;
  text-decoration: underline;
}

.hyper-link:visited,
.hyper-link:hover,
.hyper-link:active {
  color: inherit;
}
</style>

// ui/apps/console/src/pages/admin/SessionDetails.tsx
import { useParams, Link } from "react-router-dom";
import {
  CommandLineIcon,
  CheckCircleIcon,
  MinusCircleIcon,
} from "@heroicons/react/24/outline";
import { cn } from "@shellhub/design-system/cn";
import { useAdminSessionDetail } from "@/hooks/useAdminSessionDetail";
import Breadcrumb from "@/components/common/Breadcrumb";
import InfoItem from "@/components/common/InfoItem";
import { formatDateFull } from "@/utils/date";
import { sessionType } from "@/utils/session";
import PageLoader from "@/components/common/PageLoader";
import ResourceNotFound from "@/components/common/ResourceNotFound";
import { Card } from "@shellhub/design-system/primitives";

function BoolField({
  value,
  falseColor = "text-accent-red",
}: {
  value: boolean;
  falseColor?: string;
}) {
  return (
    <span
      className={cn(
        "flex items-center gap-1.5 text-sm",
        value ? "text-accent-green" : falseColor,
      )}
    >
      {value ? (
        <CheckCircleIcon className="w-4 h-4" strokeWidth={2} />
      ) : (
        <MinusCircleIcon className="w-4 h-4" strokeWidth={2} />
      )}
      {value ? "Yes" : "No"}
    </span>
  );
}

export default function AdminSessionDetails() {
  const { uid = "" } = useParams<{ uid: string }>();
  const { session, isLoading, error } = useAdminSessionDetail(uid);

  if (isLoading) {
    return <PageLoader label="Loading session" padding="fill" />;
  }

  if (error || !session) {
    return (
      <ResourceNotFound
        icon={CommandLineIcon}
        resource="Session"
        backTo="/admin/sessions"
      />
    );
  }

  const type = sessionType(session);

  return (
    <div>
      <Breadcrumb
        items={[
          { label: "Sessions", to: "/admin/sessions" },
          { label: session.uid.slice(0, 8), title: session.uid },
        ]}
      />

      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4 mb-8">
        <div className="flex items-start gap-4">
          <div className="w-14 h-14 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center text-primary shrink-0">
            <CommandLineIcon className="w-7 h-7" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-text-primary leading-tight">
              Session Details
            </h1>
            <p className="text-sm text-text-muted mt-1 max-w-xl">
              Detailed information about the selected session.
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <span
            className={cn(
              "w-2 h-2 rounded-full inline-block shrink-0",
              session.active
                ? "bg-accent-green shadow-[0_0_6px_rgba(130,165,104,0.4)]"
                : "bg-text-muted/40",
            )}
            aria-label={session.active ? "Active" : "Inactive"}
          />
          <code className="text-xs font-mono text-text-muted break-all">
            {session.uid}
          </code>
        </div>
      </div>

      <Card className="rounded-lg overflow-hidden animate-fade-in py-4">
        <div className="grid grid-cols-1 md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-border">
          <dl className="px-6 py-2 space-y-3">
            <InfoItem
              label="UID"
              value={session.uid}
              mono
              copyable
              truncate={8}
            />

            {session.device && (
              <InfoItem label="Device">
                <Link
                  to={`/admin/devices/${session.device.uid}`}
                  className="text-primary hover:underline text-sm"
                >
                  {session.device.name || session.device.uid}
                </Link>
              </InfoItem>
            )}

            <InfoItem label="Username">
              <code className="text-xs font-mono">{session.username}</code>
            </InfoItem>

            <InfoItem label="IP Address" value={session.ip_address} mono />

            <InfoItem label="Type">
              {type ? (
                <span
                  className={cn(
                    "inline-flex items-center px-2 py-0.5 text-2xs font-mono font-semibold rounded border",
                    type.color,
                  )}
                >
                  {type.label}
                </span>
              ) : (
                <span className="text-text-secondary capitalize">
                  {session.type}
                </span>
              )}
            </InfoItem>

            <InfoItem
              label="Terminal"
              value={
                session.term === "none" || !session.term ? "" : session.term
              }
            />
          </dl>

          <dl className="px-6 py-2 space-y-3">
            {session.device?.namespace && (
              <InfoItem label="Namespace" value={session.device.namespace} />
            )}

            <InfoItem label="Authenticated">
              <BoolField
                value={session.authenticated}
                falseColor="text-accent-red"
              />
            </InfoItem>

            <InfoItem label="Recorded">
              <BoolField
                value={session.recorded}
                falseColor="text-text-secondary"
              />
            </InfoItem>

            <InfoItem
              label="Started At"
              value={formatDateFull(session.started_at)}
            />

            <InfoItem
              label="Last Seen"
              value={formatDateFull(session.last_seen)}
            />
          </dl>
        </div>
      </Card>
    </div>
  );
}
