// ui/src/views/ConfirmAccount.vue
<template>
  <v-container>
    <v-card-title class="d-flex justify-center">
      Account Activation Required
    </v-card-title>

    <v-card-text class="d-flex align-center justify-center text-center">
      Thank you for registering an account on ShellHub.
      An email was sent with a confirmation link. You need to click on the link to activate your account.
      If you haven't received the email, click on Resend Email button.
    </v-card-text>

    <v-card-actions class="justify-center">
      <v-btn
        type="submit"
        color="primary"
        variant="tonal"
        block
        data-test="resendEmail-btn"
        @click="resendEmail()"
      >
        Resend Email
      </v-btn>
    </v-card-actions>

    <v-card-subtitle
      class="d-flex align-center justify-center pa-4 mx-auto"
      data-test="isCloud-card"
    >
      Back to
      <router-link
        class="ml-1"
        :to="{ name: 'login' }"
      >
        Login
      </router-link>
    </v-card-subtitle>
  </v-container>
</template>

<script setup lang="ts">
import { useRoute, useRouter } from "vue-router";
import { useStore } from "../store";
import {
  INotificationsSuccess,
} from "../interfaces/INotifications";

const store = useStore();
const router = useRouter();
const route = useRoute();

const resendEmail = async () => {
  await store.dispatch("users/resendEmail", route.query.username);
  store.dispatch(
    "snackbar/showSnackbarSuccessAction",
    INotificationsSuccess.resendEmail,
  );
  await router.push({ name: "login" });
};
</script>

// ui/apps/console/src/pages/ConfirmAccount.tsx
import { useEffect } from "react";
import { Link, Navigate, useSearchParams } from "react-router-dom";
import { EnvelopeIcon } from "@heroicons/react/24/outline";
import { Button, Callout } from "@shellhub/design-system/primitives";
import { useSignUpStore } from "../stores/signUpStore";
import { useResendEmail } from "../hooks/useResendEmail";

export default function ConfirmAccount() {
  const [searchParams] = useSearchParams();
  const resetErrors = useSignUpStore((s) => s.resetResendError);

  const username = searchParams.get("username") ?? "";

  useEffect(() => {
    resetErrors();
  }, [resetErrors]);

  const {
    handleResend,
    resendLoading,
    resendError,
    resendSuccess,
    resendCooldown,
  } = useResendEmail(username);

  if (!username) return <Navigate to="/login" replace />;

  return (
    <div className="w-full max-w-5xl mx-auto px-8 py-12 flex flex-col items-center">
      <div className="w-full max-w-sm bg-card/80 border border-border rounded-2xl p-8 backdrop-blur-sm text-center animate-slide-up">
        <div className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-primary/10 border border-primary/20 mb-5">
          <EnvelopeIcon className="w-7 h-7 text-primary" strokeWidth={1.5} />
        </div>

        <h1 className="text-lg font-semibold text-text-primary mb-3">
          Account Activation Required
        </h1>

        <p className="text-sm text-text-secondary leading-relaxed mb-6">
          Thank you for registering an account on ShellHub. An email was sent
          with a confirmation link. You need to click on the link to activate
          your account. If you haven&apos;t received the email, click on the
          Resend Email button.
        </p>

        {resendSuccess && (
          <Callout variant="success" className="mb-4">
            Confirmation email sent successfully.
          </Callout>
        )}

        {resendError && (
          <Callout variant="error" className="mb-4">
            {resendError}
          </Callout>
        )}

        <Button
          fullWidth
          loading={resendLoading}
          disabled={resendLoading || resendCooldown > 0}
          onClick={() => void handleResend()}
          className="mb-5"
        >
          {resendLoading
            ? "Sending..."
            : resendCooldown > 0
              ? `Resend Email (${resendCooldown}s)`
              : "Resend Email"}
        </Button>

        <p className="text-xs text-text-muted">
          Back to{" "}
          <Link
            to="/login"
            className="text-primary hover:text-primary/80 font-medium transition-colors"
          >
            Login
          </Link>
        </p>
      </div>
    </div>
  );
}
