// ui-react/apps/console/src/pages/ForgotPassword.tsx
import { useState, FormEvent } from "react";
import { Link } from "react-router-dom";
import {
  EnvelopeIcon,
  CheckCircleIcon,
  LockClosedIcon,
} from "@heroicons/react/24/outline";
import { recoverPassword } from "../client";

export default function ForgotPassword() {
  const [account, setAccount] = useState("");
  const [loading, setLoading] = useState(false);
  const [sent, setSent] = useState(false);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (loading) return;
    setLoading(true);
    try {
      await recoverPassword({ body: { username: account.trim() }, throwOnError: true });
    } catch {
      // Silently ignore to prevent user enumeration.
    } finally {
      setLoading(false);
      setSent(true);
    }
  };

  return (
    <div className="w-full max-w-5xl mx-auto px-8 py-12 flex flex-col items-center">
      {/* Hero */}
      <div className="text-center mb-12 animate-fade-in">
        <div className="animate-float mb-6 inline-block">
          <div className="w-20 h-20 rounded-2xl bg-primary/15 border border-primary/25 flex items-center justify-center shadow-lg shadow-primary/10">
            <LockClosedIcon className="w-10 h-10 text-primary" strokeWidth={1.2} />
          </div>
        </div>

        <p className="text-2xs font-mono font-semibold uppercase tracking-wide text-primary/80 mb-2">
          Password Recovery
        </p>
        <h1 className="text-3xl font-bold text-text-primary mb-3">
          Forgot your password?
        </h1>
        <p className="text-sm text-text-muted max-w-md mx-auto leading-relaxed">
          Enter your username or email address and we&apos;ll send you a link to
          reset your password.
        </p>
      </div>

      {/* Card */}
      <div
        className="w-full max-w-sm bg-card/80 border border-border rounded-2xl p-8 backdrop-blur-sm animate-slide-up"
        style={{ animationDelay: "200ms" }}
      >
        {sent ? (
          <div role="alert" className="flex flex-col items-center text-center gap-4">
            <div className="w-12 h-12 rounded-full bg-accent-green/15 border border-accent-green/25 flex items-center justify-center">
              <CheckCircleIcon className="w-6 h-6 text-accent-green" strokeWidth={1.5} />
            </div>
            <div>
              <p className="text-sm font-semibold text-text-primary mb-1">Check your inbox</p>
              <p className="text-xs text-text-muted leading-relaxed">
                An email with password reset instructions has been sent to your
                registered email address.
              </p>
            </div>
          </div>
        ) : (
          <form onSubmit={(e) => void handleSubmit(e)} className="space-y-5">
            <div>
              <label
                htmlFor="account"
                className="block text-2xs font-mono font-semibold uppercase tracking-label text-text-muted mb-2.5"
              >
                Username or email address
              </label>
              <input
                id="account"
                type="text"
                value={account}
                onChange={(e) => setAccount(e.target.value)}
                required
                autoFocus
                autoComplete="username"
                className="w-full px-4 py-3 bg-background border border-border rounded-lg text-sm text-text-primary font-mono placeholder:text-text-secondary focus:outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/20 transition-all duration-200"
                placeholder="username or email"
              />
            </div>

            <button
              type="submit"
              disabled={loading || !account.trim()}
              className="w-full bg-primary hover:bg-primary-600 text-white py-3 px-4 rounded-lg text-sm font-semibold disabled:opacity-dim disabled:cursor-not-allowed transition-all duration-200 mt-1 flex items-center justify-center gap-2"
            >
              {loading ? (
                <>
                  <span className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  <span className="font-mono text-xs">Sending...</span>
                </>
              ) : (
                <>
                  <EnvelopeIcon className="w-4 h-4" strokeWidth={2} />
                  Reset Password
                </>
              )}
            </button>
          </form>
        )}
      </div>

      {/* Back to login */}
      <div
        className="mt-8 animate-fade-in"
        style={{ animationDelay: "600ms" }}
      >
        <Link
          to="/login"
          className="text-xs text-text-muted hover:text-text-secondary transition-colors"
        >
          &larr; Back to login
        </Link>
      </div>
    </div>
  );
}

// ui/src/views/ForgotPassword.vue
<template>
  <v-container>
    <v-col>
      <v-slide-y-reverse-transition>
        <v-card-text v-if="postSuccessful" class="text-center" data-test="success-text">
          <strong>An email with password reset instructions has been sent to your registered email address. Please check your inbox.
          </strong>
        </v-card-text>
      </v-slide-y-reverse-transition>
    </v-col>

    <v-container>
      <div v-if="!postSuccessful">
        <v-card-title class="text-center" data-test="title-text">
          Forgot your password
        </v-card-title>
        <v-card-text class="text-center" data-test="body-text">
          Please insert the email associated with the account you'd like to request a password reset for
        </v-card-text>
        <v-form v-model="validForm" @submit.prevent="sendEmail">

          <v-text-field
            color="primary"
            prepend-inner-icon="mdi-account"
            v-model="account"
            :error-messages="accountError"
            required
            label="Username or email address"
            variant="underlined"
            data-test="account-text"
          />
          <v-card-actions class="justify-center pa-0">
            <v-btn
              :disabled="!validForm"
              data-test="forgotPassword-btn"
              color="primary"
              variant="elevated"
              block
              @click="sendEmail"
            >
              RESET PASSWORD
            </v-btn>
          </v-card-actions>

        </v-form>
      </div>
      <v-card-subtitle
        class="d-flex align-center justify-center pa-4 mx-auto"
        data-test="isCloud-card"
      >
        Back to
        <router-link class="ml-1 text-decoration-none" :to="{ name: 'login' }">
          <strong>Login</strong>
        </router-link>
      </v-card-subtitle>
    </v-container>

  </v-container>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useField } from "vee-validate";
import * as yup from "yup";
import { useStore } from "../store";
import handleError from "../utils/handleError";

const store = useStore();
const postSuccessful = ref(false);
const validForm = ref(false);

const { value: account, errorMessage: accountError } = useField<string | undefined>(
  "account",
  yup
    .string()
    .required()
    .min(3)
    .max(255)
    .test("account-error", "The field only accepts the special characters _, ., -, and @.", (value) => {
      const regex = /^[a-zA-Z0-9_.@-\s]*$/;
      return regex.test(value || "");
    })
    .test("white-spaces", "The field cannot contain white spaces.", (value) => {
      const regex = /\s/;
      return !regex.test(value || "");
    }),
  {
    initialValue: "",
  },
);

const sendEmail = async () => {
  if (accountError.value) {
    return;
  }

  try {
    await store.dispatch("users/recoverPassword", account.value);
    postSuccessful.value = true;
  } catch (error) {
    handleError(error);
  }
};
</script>
