// ui/apps/console/src/pages/Setup.tsx
import { useState, useEffect, useCallback, FormEvent } from "react";
import { isSdkError } from "../api/errors";
import { useNavigate } from "react-router-dom";
import { CheckIcon, ExclamationCircleIcon } from "@heroicons/react/24/outline";
import { setup } from "../client";
import { getConfig } from "../env";
import { validate, type FormErrors } from "./setup/validate";
import InputField from "@/components/common/fields/InputField";
import PasswordField from "@/components/common/fields/PasswordField";
import { Button } from "@shellhub/design-system/primitives";

const STEP_ONBOARDING = 1;
const STEP_ACCOUNT = 2;

export default function Setup() {
  const navigate = useNavigate();
  const config = getConfig();

  const isCommunity = !config.cloud && !config.enterprise;
  const showOnboarding = isCommunity && !!config.onboardingUrl;

  const [step, setStep] = useState(
    showOnboarding ? STEP_ONBOARDING : STEP_ACCOUNT,
  );
  const [name, setName] = useState("");
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState(false);
  const [surveyCompleted, setSurveyCompleted] = useState(false);

  const errors = validate({ name, username, email, password, confirmPassword });

  const disableCreateAccountButton = loading || Object.keys(errors).length > 0;

  const onboardingUrl = (() => {
    if (!config.onboardingUrl) return "";
    const params = new URLSearchParams({
      consent_to_contact: "accepted",
      source: "self-hosted",
      embed: "true",
      instance_domain: window.location.hostname,
    });
    if (import.meta.env.DEV) params.append("preview", "true");
    return `${config.onboardingUrl}?${params.toString()}`;
  })();

  const handleMessage = useCallback(
    (event: MessageEvent) => {
      if (!config.onboardingUrl) return;
      try {
        const origin = new URL(config.onboardingUrl).origin;
        if (event.origin !== origin) return;
      } catch {
        return;
      }
      if (event.data === "formbricksSurveyCompleted") {
        setSurveyCompleted(true);
      }
    },
    [config.onboardingUrl],
  );

  useEffect(() => {
    if (!showOnboarding) return;
    window.addEventListener("message", handleMessage);
    return () => window.removeEventListener("message", handleMessage);
  }, [showOnboarding, handleMessage]);

  useEffect(() => {
    if (success) {
      const timer = setTimeout(
        () => void navigate("/login", { replace: true }),
        3000,
      );
      return () => clearTimeout(timer);
    }
  }, [success, navigate]);

  const handleBlur = (field: string) => {
    setTouched((prev) => ({ ...prev, [field]: true }));
  };

  const showError = (field: keyof FormErrors) =>
    touched[field] ? errors[field] : undefined;

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();

    setTouched({
      name: true,
      username: true,
      email: true,
      password: true,
      confirmPassword: true,
    });

    if (Object.keys(errors).length > 0) return;

    setLoading(true);
    setError("");

    try {
      await setup({
        body: { name, username, email, password },
        throwOnError: true,
      });
      setSuccess(true);
    } catch (err: unknown) {
      if (isSdkError(err) && err.status === 409) {
        setError("Setup has already been completed.");
      } else {
        setError("An error occurred. Please try again.");
      }
    } finally {
      setLoading(false);
    }
  };

  const totalSteps = showOnboarding ? 2 : 1;
  const displayStep = step === STEP_ONBOARDING ? 1 : totalSteps;

  if (success) {
    return (
      <div className="w-full max-w-sm mx-auto animate-fade-in">
        <div className="bg-surface border border-border rounded-lg overflow-hidden">
          <div className="px-8 pt-8 pb-6 border-b border-border bg-card/50">
            <div className="flex justify-center mb-5">
              <img src="/logo.svg" alt="ShellHub" className="h-7" />
            </div>
            <p className="text-center text-2xs font-mono text-text-muted tracking-wider uppercase">
              Initial Setup
            </p>
          </div>

          <div className="p-8 text-center">
            <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-accent-green/10 mb-4">
              <CheckIcon
                className="w-6 h-6 text-accent-green"
                strokeWidth={2}
              />
            </div>
            <h3 className="text-sm font-semibold text-text-primary mb-2">
              Account created successfully
            </h3>
            <p className="text-xs text-text-secondary leading-relaxed">
              Redirecting to login in a few seconds...
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      className={`w-full mx-auto animate-fade-in ${step === STEP_ONBOARDING ? "max-w-lg" : "max-w-sm"}`}
    >
      <div className="bg-surface border border-border rounded-lg overflow-hidden">
        <div className="px-8 pt-8 pb-6 border-b border-border bg-card/50">
          <div className="flex justify-center mb-5">
            <img src="/logo.svg" alt="ShellHub" className="h-7" />
          </div>
          <h1 className="text-center text-sm font-semibold text-text-primary mb-1">
            Welcome to ShellHub
          </h1>
          <p className="text-center text-2xs font-mono text-text-muted tracking-wider uppercase">
            Initial Setup
          </p>

          {showOnboarding && (
            <div className="flex items-center justify-center gap-2 mt-4">
              {Array.from({ length: totalSteps }, (_, i) => (
                <StepIndicator key={i} index={i} current={displayStep} />
              ))}
            </div>
          )}
        </div>

        <div className="p-8">
          {error && (
            <div className="flex items-start gap-2 bg-accent-red/8 border border-accent-red/20 text-accent-red px-3.5 py-2.5 rounded-md text-xs font-mono animate-slide-down mb-5">
              <ExclamationCircleIcon
                className="w-3.5 h-3.5 shrink-0 mt-0.5"
                strokeWidth={2}
              />
              {error}
            </div>
          )}

          {step === STEP_ONBOARDING && (
            <div className="space-y-5">
              <p className="text-xs text-text-secondary leading-relaxed text-center">
                Help us improve ShellHub by sharing your feedback
              </p>

              <div className="relative h-[60dvh] overflow-auto rounded-md border border-border">
                <iframe
                  src={onboardingUrl}
                  title="Onboarding survey"
                  className="absolute inset-0 w-full h-full border-0"
                />
              </div>

              <Button
                fullWidth
                disabled={!surveyCompleted}
                onClick={() => setStep(STEP_ACCOUNT)}
              >
                Continue
              </Button>
            </div>
          )}

          {step === STEP_ACCOUNT && (
            <form onSubmit={(e) => void handleSubmit(e)} className="space-y-4">
              <p className="text-xs text-text-secondary leading-relaxed mb-1">
                Set up your admin account with your personal information.
              </p>

              <InputField
                id="name"
                label="Name"
                value={name}
                onChange={setName}
                onBlur={() => handleBlur("name")}
                error={showError("name")}
                placeholder="Your name"
                maxLength={64}
              />

              <InputField
                id="username"
                label="Username"
                value={username}
                onChange={setUsername}
                onBlur={() => handleBlur("username")}
                error={showError("username")}
                placeholder="username"
                maxLength={32}
              />

              <InputField
                id="email"
                label="Email"
                type="email"
                value={email}
                onChange={setEmail}
                onBlur={() => handleBlur("email")}
                error={showError("email")}
                placeholder="you@example.com"
              />

              <PasswordField
                id="password"
                label="Password"
                value={password}
                onChange={setPassword}
                onBlur={() => handleBlur("password")}
                error={showError("password")}
                placeholder="Min. 5 characters"
              />

              <PasswordField
                id="confirmPassword"
                label="Confirm Password"
                value={confirmPassword}
                onChange={setConfirmPassword}
                onBlur={() => handleBlur("confirmPassword")}
                error={showError("confirmPassword")}
                placeholder="Re-enter password"
              />

              <div className="flex gap-3 pt-1">
                {showOnboarding && (
                  <Button
                    variant="secondary"
                    className="flex-1"
                    onClick={() => setStep(STEP_ONBOARDING)}
                  >
                    Back
                  </Button>
                )}
                <Button
                  type="submit"
                  loading={loading}
                  disabled={disableCreateAccountButton}
                  className={showOnboarding ? "flex-[2]" : "w-full"}
                >
                  {loading ? "Creating..." : "Create Account"}
                </Button>
              </div>
            </form>
          )}
        </div>
      </div>

      <p className="text-center text-2xs font-mono text-text-muted/40 mt-6">
        ShellHub &mdash; Secure Remote Access
      </p>
    </div>
  );
}

function StepIndicator({ index, current }: { index: number; current: number }) {
  const stepNum = index + 1;
  return (
    <>
      {index > 0 && <div className="w-6 h-px bg-border" />}
      <StepDot active={current === stepNum} label={String(stepNum)} />
    </>
  );
}

function StepDot({ active, label }: { active: boolean; label: string }) {
  return (
    <div
      className={`w-5 h-5 rounded-full flex items-center justify-center text-3xs font-mono font-bold transition-colors ${
        active ? "bg-primary text-white" : "bg-border text-text-muted"
      }`}
    >
      {label}
    </div>
  );
}

// ui/src/views/Setup.vue
<template>
  <v-container class="pb-0 my-0">
    <v-alert
      v-if="alertMessage"
      :type="alertType"
      variant="tonal"
      :text="alertMessage"
      class="mb-4"
      data-test="user-status-alert"
    />
    <v-form @submit.prevent="setupAccount">
      <v-card-title
        class="text-center"
        data-test="welcome-title"
      >
        Welcome to ShellHub!
      </v-card-title>
      <v-window v-model="step">
        <v-window-item :value="SetupStep.Sign">
          <v-card-subtitle
            class="text-wrap text-justify px-0"
            data-test="subtitle-1"
          >
            To set up your account, please run the following command in your terminal to generate a signature.
            Use the generated signature in the "Sign" field below to proceed.
          </v-card-subtitle>
          <CopyCommandField
            command="./bin/setup"
            label="Setup Command"
            class="my-4"
            data-test="setup-command-field"
          />
          <v-text-field
            v-model="sign"
            color="primary"
            prepend-inner-icon="mdi-key"
            :disabled="!!hasQuery"
            :error-messages="signError"
            required
            label="Sign"
            data-test="sign-text"
          />
          <v-btn
            :disabled="!hasSign"
            data-test="sign-btn"
            color="primary"
            variant="tonal"
            block
            text="Next"
            @click="step = showOnboardingStep ? SetupStep.Onboarding : SetupStep.Account"
          />
        </v-window-item>

        <v-window-item
          v-if="showOnboardingStep"
          :value="SetupStep.Onboarding"
        >
          <v-card-subtitle
            class="text-wrap text-center mb-4"
            data-test="subtitle-2"
          >
            Help us improve ShellHub by sharing your feedback
          </v-card-subtitle>

          <div style="position: relative; height:60dvh; overflow:auto;">
            <iframe
              :src="onboardingUrl"
              frameborder="0"
              style="position: absolute; left:0; top:0; width:100%; height:100%; border:0;"
            />
          </div>

          <v-card-actions class="mt-4">
            <v-btn
              color="primary"
              variant="text"
              @click="step = SetupStep.Sign"
            >
              Back
            </v-btn>
            <v-spacer />
            <v-btn
              :disabled="!surveyCompleted"
              color="primary"
              variant="tonal"
              data-test="continue-btn"
              @click="step = SetupStep.Account"
            >
              Continue
            </v-btn>
          </v-card-actions>
        </v-window-item>

        <v-window-item :value="SetupStep.Account">
          <v-card-subtitle
            class="text-wrap text-center mb-3"
            data-test="subtitle-3"
          >
            Please complete the following form to set up your account with your personal information.
          </v-card-subtitle>
          <v-text-field
            v-model="name"
            color="primary"
            prepend-inner-icon="mdi-account"
            :error-messages="nameError"
            required
            label="Name"
            data-test="name-text"
          />

          <v-text-field
            v-model="username"
            color="primary"
            prepend-inner-icon="mdi-account"
            :error-messages="usernameError"
            required
            label="Username"
            data-test="username-text"
          />

          <v-text-field
            v-model="email"
            color="primary"
            prepend-inner-icon="mdi-email"
            :error-messages="emailError"
            required
            label="Email"
            data-test="email-text"
          />

          <v-text-field
            v-model="password"
            color="primary"
            prepend-inner-icon="mdi-lock"
            :append-inner-icon="showPassword ? 'mdi-eye' : 'mdi-eye-off'"
            :error-messages="passwordError"
            label="Password"
            required
            data-test="password-text"
            :type="showPassword ? 'text' : 'password'"
            @click:append-inner="showPassword = !showPassword"
          />

          <v-text-field
            v-model="passwordConfirm"
            color="primary"
            prepend-inner-icon="mdi-lock"
            :append-inner-icon="showConfirmPassword ? 'mdi-eye' : 'mdi-eye-off'"
            :error-messages="passwordConfirmError"
            label="Confirm Password"
            required
            data-test="password-confirm-text"
            :type="showConfirmPassword ? 'text' : 'password'"
            @click:append-inner="showConfirmPassword = !showConfirmPassword"
          />

          <v-card-actions class="mt-4">
            <v-btn
              color="primary"
              variant="text"
              @click="step = showOnboardingStep ? SetupStep.Onboarding : SetupStep.Sign"
            >
              Back
            </v-btn>
            <v-spacer />
            <v-btn
              :disabled="!isFormValid"
              type="submit"
              data-test="setup-account-btn"
              color="primary"
              variant="tonal"
              text="Create Account"
            />
          </v-card-actions>
        </v-window-item>
      </v-window>
    </v-form>
  </v-container>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import { useRouter, useRoute } from "vue-router";
import { useField } from "vee-validate";
import { useEventListener } from "@vueuse/core";
import * as yup from "yup";
import useUsersStore from "@/store/modules/users";
import CopyCommandField from "@/components/Fields/CopyCommandField.vue";
import { envVariables } from "@/envVariables";

enum SetupStep {
  Sign = 1,
  Onboarding = 2,
  Account = 3,
}

const usersStore = useUsersStore();
const router = useRouter();
const route = useRoute();

const showPassword = ref(false);
const showConfirmPassword = ref(false);
const alertMessage = ref("");
const alertType = ref<"success" | "error">("success");
const step = ref<SetupStep>(SetupStep.Sign);
const surveyCompleted = ref(false);
const hasQuery = computed(() => route.query.sign as string);

// Onboarding survey is only available in Community Edition
const showOnboardingStep = computed(() => envVariables.isCommunity && !!envVariables.onboardingUrl);

const onboardingUrl = computed(() => {
  if (!envVariables.onboardingUrl) {
    return "";
  }

  const baseUrl = envVariables.onboardingUrl;
  const params = new URLSearchParams({
    consent_to_contact: "accepted",
    source: "self-hosted",
    embed: "true",
    instance_domain: window.location.hostname,
  });

  if (import.meta.env.DEV) {
    params.append("preview", "true");
  }

  return `${baseUrl}?${params.toString()}`;
});

const {
  value: sign,
  errorMessage: signError,
} = useField<string>("sign", yup.string().required(), {
  initialValue: route.query.sign as string,
});

const {
  value: name,
  errorMessage: nameError,
} = useField<string>("name", yup.string().required()
  .min(1, "Your name should be 1-64 characters long")
  .max(64, "Your name should be 1-64 characters long"), {
  initialValue: "",
});

const {
  value: username,
  errorMessage: usernameError,
} = useField<string>("username", yup.string()
  .required("Username is required")
  .min(3, "Username must be at least 3 characters")
  .max(32, "Username must not exceed 32 characters")
  .matches(/^[a-z0-9-_.@]+$/, "Username can only contain lowercase letters, numbers, and certain symbols"), {
  initialValue: "",
});

const {
  value: email,
  errorMessage: emailError,
} = useField<string>("email", yup.string().email().required(), {
  initialValue: "",
});

const {
  value: password,
  errorMessage: passwordError,
} = useField<string>("password", yup.string().required()
  .min(5, "Password must be at least 5 characters long")
  .max(32, "Password must not exceed 32 characters"), {
  initialValue: "",
});

const {
  value: passwordConfirm,
  errorMessage: passwordConfirmError,
} = useField<string>("passwordConfirm", yup.string().required()
  .test("passwords-match", "Passwords do not match", (value) => password.value === value), {
  initialValue: "",
});

const hasSign = computed(() => !!sign.value);

const isFormValid = computed(() => (
  name.value
  && username.value
  && email.value
  && password.value
  && passwordConfirm.value
  && !nameError.value
  && !usernameError.value
  && !emailError.value
  && !passwordError.value
  && !passwordConfirmError.value
));

// Listen for FormBricks survey completion
useEventListener(window, "message", (event: MessageEvent) => {
  // Verify the message is from FormBricks
  if (!envVariables.onboardingUrl) return;

  try {
    const formbricksOrigin = new URL(envVariables.onboardingUrl).origin;
    if (event.origin !== formbricksOrigin) {
      return;
    }
  } catch {
    return;
  }

  // Check if the survey was completed
  // FormBricks sends the completion event as a simple string
  if (event.data === "formbricksSurveyCompleted") {
    surveyCompleted.value = true;
  }
});

onMounted(() => {
  if (hasQuery.value) {
    step.value = showOnboardingStep.value ? SetupStep.Onboarding : SetupStep.Account;
  }
});

const setupAccount = async () => {
  if (isFormValid.value) {
    try {
      const setupData = {
        sign: sign.value,
        name: name.value,
        username: username.value,
        email: email.value,
        password: password.value,
      };

      await usersStore.setup(setupData);

      alertType.value = "success";
      alertMessage.value = "Successfully created your account. Redirecting to login...";
      setTimeout(() => { void router.push({ name: "Login" }); }, 3000);
    } catch {
      alertType.value = "error";
      alertMessage.value = "An error occurred. Please check if the sign matches the same generated by the command and try again.";
    }
  }
};
</script>
