// ui/apps/console/src/pages/admin/namespaces/NamespaceDetails.tsx
import { useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import {
  ServerStackIcon,
  PencilSquareIcon,
  TrashIcon,
  InformationCircleIcon,
  Cog6ToothIcon,
} from "@heroicons/react/24/outline";
import { cn } from "@shellhub/design-system/cn";
import { useAdminNamespace } from "@/hooks/useAdminNamespaces";
import Breadcrumb from "@/components/common/Breadcrumb";
import DataTable, { type Column } from "@/components/common/DataTable";
import EditNamespaceDrawer from "./EditNamespaceDrawer";
import DeleteNamespaceDialog from "./DeleteNamespaceDialog";
import { formatDateFull } from "@/utils/date";
import { formatMaxDevices } from "./utils";
import InfoItem from "@/components/common/InfoItem";
import PageLoader from "@/components/common/PageLoader";
import {
  Badge,
  Button,
  Card,
  IconButton,
} from "@shellhub/design-system/primitives";

const ZERO_DATE = "0001-01-01T00:00:00Z";

type Member = NonNullable<
  NonNullable<ReturnType<typeof useAdminNamespace>["data"]>["members"]
>[number];

export default function NamespaceDetails() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data: namespace, isLoading, error } = useAdminNamespace(id ?? "");

  const [editOpen, setEditOpen] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);

  if (isLoading) {
    return <PageLoader label="Loading namespace details" />;
  }

  if (error || !namespace) {
    return (
      <div className="text-center py-24">
        <ServerStackIcon
          className="w-10 h-10 text-text-muted/30 mx-auto mb-3"
          strokeWidth={1}
        />
        <p className="text-sm text-text-muted mb-2">Namespace not found</p>
        <Link
          to="/admin/namespaces"
          className="text-sm text-primary hover:underline"
        >
          Back to namespaces
        </Link>
      </div>
    );
  }

  const ownerMember = namespace.members?.find((m) => m.id === namespace.owner);
  const ownerLabel = ownerMember?.email || namespace.owner;
  const totalDevices =
    (namespace.devices_accepted_count || 0) +
    (namespace.devices_pending_count || 0) +
    (namespace.devices_rejected_count || 0);

  const memberColumns: Column<Member>[] = [
    {
      key: "email",
      header: "Email",
      render: (member) =>
        member.id ? (
          <Link
            to={`/admin/users/${member.id}`}
            className="text-sm text-primary hover:underline"
          >
            {member.email || member.id}
          </Link>
        ) : (
          <span className="text-sm text-text-primary">
            {member.email || "\u2014"}
          </span>
        ),
    },
    {
      key: "role",
      header: "Role",
      render: (member) => (
        <Badge color="primary" className="capitalize">
          {member.role || "member"}
        </Badge>
      ),
    },
    {
      key: "added",
      header: "Added",
      render: (member) => (
        <span className="text-xs text-text-secondary">
          {member.added_at && member.added_at !== ZERO_DATE
            ? formatDateFull(member.added_at)
            : "\u2014"}
        </span>
      ),
    },
  ];

  return (
    <div className="animate-fade-in">
      <Breadcrumb
        items={[
          { label: "Namespaces", to: "/admin/namespaces" },
          { label: namespace.name },
        ]}
      />

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 mb-8">
        <div className="flex items-start gap-4">
          <div className="w-14 h-14 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center shrink-0">
            <ServerStackIcon className="w-7 h-7 text-primary" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-text-primary">
              {namespace.name}
            </h1>
          </div>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          <Button
            variant="secondary"
            icon={<PencilSquareIcon className="w-4 h-4" />}
            onClick={() => setEditOpen(true)}
          >
            Edit
          </Button>
          <IconButton
            variant="danger"
            size="lg"
            title="Delete namespace"
            aria-label={`Delete ${namespace.name}`}
            className="border border-border"
            onClick={() => setDeleteOpen(true)}
          >
            <TrashIcon className="w-4 h-4" />
          </IconButton>
        </div>
      </div>

      {/* Info Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        {/* Properties Card */}
        <Card className="p-5 space-y-4">
          <h3 className="text-xs font-semibold text-text-primary flex items-center gap-2">
            <InformationCircleIcon className="w-4 h-4 text-primary" />
            Properties
          </h3>
          <dl className="space-y-3">
            <InfoItem label="Name" value={namespace.name} />
            <InfoItem
              label="Tenant ID"
              value={namespace.tenant_id}
              mono
              copyable
            />
            <InfoItem label="Owner">
              <Link
                to={`/admin/users/${namespace.owner}`}
                className="text-sm text-primary hover:underline"
              >
                {ownerLabel}
              </Link>
            </InfoItem>
            <InfoItem
              label="Created"
              value={formatDateFull(namespace.created_at)}
            />
          </dl>
        </Card>

        {/* Settings Card */}
        <Card className="p-5 space-y-4">
          <h3 className="text-xs font-semibold text-text-primary flex items-center gap-2">
            <Cog6ToothIcon className="w-4 h-4 text-primary" />
            Settings
          </h3>
          <dl className="space-y-3">
            <InfoItem
              label="Max Devices"
              value={formatMaxDevices(namespace.max_devices)}
            />
            <InfoItem label="Session Recording">
              <span
                className={cn(
                  "inline-flex items-center px-2 py-0.5 text-2xs font-semibold rounded-md",
                  namespace.settings?.session_record
                    ? "bg-accent-green/10 text-accent-green border border-accent-green/20"
                    : "bg-accent-yellow/10 text-accent-yellow border border-accent-yellow/20",
                )}
              >
                {namespace.settings?.session_record ? "Enabled" : "Disabled"}
              </span>
            </InfoItem>
            <InfoItem label="Auto-Accept Devices">
              <span
                className={cn(
                  "inline-flex items-center px-2 py-0.5 text-2xs font-semibold rounded-md",
                  namespace.settings?.device_auto_accept
                    ? "bg-accent-green/10 text-accent-green border border-accent-green/20"
                    : "bg-accent-yellow/10 text-accent-yellow border border-accent-yellow/20",
                )}
              >
                {namespace.settings?.device_auto_accept
                  ? "Enabled"
                  : "Disabled"}
              </span>
            </InfoItem>
            {namespace.settings?.connection_announcement && (
              <InfoItem label="Connection Announcement">
                <div className="overflow-x-auto rounded-lg bg-surface border border-border p-3">
                  <pre className="text-xs font-mono text-text-primary whitespace-pre">
                    {namespace.settings.connection_announcement}
                  </pre>
                </div>
              </InfoItem>
            )}
            <div className="flex items-center gap-6">
              <InfoItem label="Total Devices" value={String(totalDevices)} />
              <InfoItem
                label="Accepted"
                value={String(namespace.devices_accepted_count || 0)}
              />
              <InfoItem
                label="Pending"
                value={String(namespace.devices_pending_count || 0)}
              />
              <InfoItem
                label="Rejected"
                value={String(namespace.devices_rejected_count || 0)}
              />
            </div>
          </dl>
        </Card>
      </div>

      {/* Members Section */}
      <Card className="overflow-hidden">
        <div className="px-5 py-4 border-b border-border">
          <h3 className="text-xs font-semibold text-text-primary">
            Members ({namespace.members?.length || 0})
          </h3>
        </div>
        <DataTable<Member>
          columns={memberColumns}
          data={namespace.members ?? []}
          rowKey={(m, i) => m.id || m.email || `member-${i}`}
          label="Members"
          noWrapper
          emptyMessage="No members"
        />
      </Card>

      <EditNamespaceDrawer
        open={editOpen}
        onClose={() => setEditOpen(false)}
        namespace={namespace}
      />

      <DeleteNamespaceDialog
        open={deleteOpen}
        onClose={() => setDeleteOpen(false)}
        namespace={
          namespace
            ? { tenant_id: namespace.tenant_id, name: namespace.name }
            : null
        }
        onDeleted={() => void navigate("/admin/namespaces")}
      />
    </div>
  );
}

// ui/admin/src/views/NamespaceDetails.vue
<template>
  <div class="d-flex pa-0 align-center">
    <h1>Namespace Details</h1>
  </div>
  <v-card
    v-if="namespace.tenant_id"
    class="mt-2 border rounded bg-background"
    elevation="0"
  >
    <v-card-title
      class="pa-4 d-flex align-center justify-space-between bg-v-theme-surface"
    >
      <span class="text-h6 ml-2 d-flex align-center ga-2">
        {{ namespace.name || 'Namespace' }}
        <v-chip
          v-if="namespace.type"
          :color="namespace.type === 'team' ? 'primary' : 'default'"
          data-test="namespace-type-chip"
          class="text-capitalize"
        >
          {{ namespace.type }}
        </v-chip>
      </span>

      <v-menu
        location="bottom"
        scrim
        eager
      >
        <template #activator="{ props }">
          <v-btn
            v-bind="props"
            variant="plain"
            class="border rounded bg-v-theme-background"
            density="comfortable"
            size="default"
            icon="mdi-format-list-bulleted"
            data-test="namespace-actions-menu-btn"
          />
        </template>

        <v-list
          class="bg-v-theme-surface"
          lines="two"
          density="compact"
        >
          <v-list-item
            data-test="namespace-edit-btn"
            @click="namespaceEdit = true"
          >
            <div class="d-flex align-center">
              <v-icon class="mr-2">mdi-pencil</v-icon>
              <v-list-item-title>Edit namespace</v-list-item-title>
            </div>
          </v-list-item>

          <v-list-item
            data-test="namespace-delete-btn"
            @click="namespaceDelete = true"
          >
            <div class="d-flex align-center">
              <v-icon class="mr-2">mdi-delete</v-icon>
              <v-list-item-title>Delete namespace</v-list-item-title>
            </div>
          </v-list-item>

          <div class="px-2 py-1" />
        </v-list>
      </v-menu>
    </v-card-title>

    <v-divider />

    <v-card-text class="pa-4 pt-0">
      <v-row class="py-3">
        <v-col
          cols="12"
          md="6"
          class="my-0 py-0"
        >
          <div data-test="namespace-name-field">
            <div class="item-title">Name:</div>
            <p class="text-truncate">{{ namespace.name }}</p>
          </div>

          <div data-test="namespace-tenant-id-field">
            <div class="item-title">Tenant ID:</div>
            <p class="text-truncate">
              <code>{{ namespace.tenant_id }}</code>
            </p>
          </div>

          <div data-test="namespace-owner-field">
            <div class="item-title">Owner:</div>
            <router-link
              :to="{ name: 'userDetails', params: { id: namespace.owner } }"
              class="unstyled-link text-decoration-underline cursor-pointer"
            >
              {{ getOwnerLabel(namespace) }}
            </router-link>
          </div>

          <div data-test="namespace-devices-field">
            <div class="item-title">Total Devices:</div>
            <p>{{ sumDevicesCount(namespace) }}</p>
          </div>

          <div
            class="d-flex align-center flex-wrap mt-2"
            data-test="namespace-devices-breakdown"
          >
            <div
              class="mr-6"
              data-test="namespace-devices-accepted"
            >
              <div class="item-title">Accepted:</div>
              <p>{{ namespace.devices_accepted_count || 0 }}</p>
            </div>
            <div
              class="mr-6"
              data-test="namespace-devices-pending"
            >
              <div class="item-title">Pending:</div>
              <p>{{ namespace.devices_pending_count || 0 }}</p>
            </div>
            <div data-test="namespace-devices-rejected">
              <div class="item-title">Rejected:</div>
              <p>{{ namespace.devices_rejected_count || 0 }}</p>
            </div>
          </div>
        </v-col>

        <v-col
          cols="12"
          md="6"
          class="my-0 py-0"
        >
          <div
            v-if="namespace.created_at"
            data-test="namespace-created-field"
          >
            <div class="item-title">Created:</div>
            <p>{{ formatFullDateTime(namespace.created_at) }}</p>
          </div>

          <div data-test="namespace-max-devices-field">
            <div class="item-title">Max Devices:</div>
            <p>{{ namespace.max_devices === -1 ? 'Unlimited' : namespace.max_devices }}</p>
          </div>

          <div
            v-if="namespace.settings"
            data-test="namespace-session-record-field"
          >
            <div class="item-title">Session Record:</div>
            <v-chip
              size="small"
              :color="namespace.settings.session_record ? 'success' : 'default'"
            >
              {{ namespace.settings.session_record ? 'Enabled' : 'Disabled' }}
            </v-chip>
          </div>

          <div
            v-if="namespace.settings?.connection_announcement"
            data-test="namespace-connection-announcement-field"
          >
            <div class="item-title">Connection Announcement:</div>
            <p>{{ namespace.settings.connection_announcement }}</p>
          </div>
        </v-col>
      </v-row>

      <v-divider class="my-4" />

      <div data-test="namespace-members-section">
        <h3 class="text-h6 mb-3">
          Members ({{ namespace.members?.length || 0 }})
        </h3>

        <v-list
          v-if="namespace.members?.length"
          class="bg-transparent"
          data-test="namespace-members-list"
        >
          <v-list-item
            v-for="(member, index) in namespace.members"
            :key="index"
            class="border rounded mb-2 bg-v-theme-surface"
            data-test="namespace-member-item"
          >
            <v-list-item-title class="d-flex align-center mb-2">
              <router-link
                :to="{ name: 'userDetails', params: { id: namespace.owner } }"
                class="unstyled-link text-decoration-underline cursor-pointer"
              >
                {{ getOwnerLabel(namespace) }}
              </router-link>
              <v-chip
                size="small"
                class="ml-2 text-capitalize"
                data-test="namespace-member-role"
              >
                <v-icon
                  :icon="getRoleIcon(member.role)"
                  class="mr-1"
                  size="small"
                />
                {{ getRoleLabel(member.role) }}
              </v-chip>
              <v-chip
                size="small"
                class="ml-2 text-capitalize"
                data-test="namespace-member-status"
              >
                {{ member.status }}
              </v-chip>
            </v-list-item-title>

            <v-list-item-subtitle class="d-flex flex-column">
              <span
                class="text-caption"
                data-test="namespace-member-id"
              >
                <strong>ID:</strong> <code>{{ member.id }}</code>
              </span>
              <span
                v-if="member.added_at && member.added_at !== '0001-01-01T00:00:00Z'"
                class="text-caption"
                data-test="namespace-member-added"
              >
                <strong>Added:</strong> {{ formatFullDateTime(member.added_at) }}
              </span>
              <span
                v-if="member.expires_at && member.expires_at !== '0001-01-01T00:00:00Z'"
                class="text-caption"
                data-test="namespace-member-expires"
              >
                <strong>Expires:</strong> {{ formatFullDateTime(member.expires_at) }}
              </span>
            </v-list-item-subtitle>
          </v-list-item>
        </v-list>

        <p
          v-else
          class="text-disabled text-center py-4"
        >
          No members found
        </p>
      </div>
    </v-card-text>
  </v-card>

  <v-card
    v-else
    class="mt-2 pa-4 bg-v-theme-surface"
  >
    <p class="text-center">Something is wrong, try again!</p>
  </v-card>

  <NamespaceEdit
    v-if="hasNamespace"
    v-model="namespaceEdit"
    :namespace="namespace"
    @update="fetchNamespaceDetails"
  />

  <NamespaceDelete
    v-if="hasNamespace"
    v-model="namespaceDelete"
    :tenant="namespace.tenant_id"
    :name="namespace.name || 'Namespace'"
  />
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import useNamespacesStore from "@admin/store/modules/namespaces";
import NamespaceEdit from "@admin/components/Namespace/NamespaceEdit.vue";
import NamespaceDelete from "@admin/components/Namespace/NamespaceDelete.vue";
import { IAdminNamespace } from "@admin/interfaces/INamespace";
import useSnackbar from "@/helpers/snackbar";
import handleError from "@/utils/handleError";
import { formatFullDateTime } from "@/utils/date";

const namespacesStore = useNamespacesStore();
const snackbar = useSnackbar();
const route = useRoute();

const loading = ref(false);
const namespaceEdit = ref(false);
const namespaceDelete = ref(false);
const namespace = computed(() => namespacesStore.namespace);
const hasNamespace = computed(() => !!namespace.value.tenant_id);
const namespaceId = computed(() => route.params.id);

const fetchNamespaceDetails = async () => {
  try {
    loading.value = true;
    await namespacesStore.fetchNamespaceById(namespaceId.value as string);
  } catch (error) {
    snackbar.showError("Failed to fetch namespace details.");
    handleError(error);
  } finally {
    loading.value = false;
  }
};

onMounted(async () => {
  await fetchNamespaceDetails();
});

const sumDevicesCount = (namespace: IAdminNamespace) => {
  const { devices_accepted_count: acceptedCount, devices_pending_count: pendingCount, devices_rejected_count: rejectedCount } = namespace;
  return (acceptedCount + pendingCount + rejectedCount) || 0;
};

const roleConfig: Record<string, { label: string; icon: string; color: string }> = {
  owner: { label: "owner", icon: "mdi-crown", color: "warning" },
  administrator: { label: "admin", icon: "mdi-shield-account", color: "error" },
  operator: { label: "operator", icon: "mdi-account-cog", color: "primary" },
  observer: { label: "observer", icon: "mdi-eye", color: "info" },
};

const getRoleLabel = (role: string) => {
  if (!role) return "member";
  return roleConfig[role]?.label || role;
};

const getRoleIcon = (role: string) => {
  if (!role) return "mdi-account";
  return roleConfig[role]?.icon || "mdi-account";
};

const getOwnerLabel = (namespace: IAdminNamespace) => {
  const owner = namespace.members?.find(
    (member) => member.id === namespace.owner,
  );

  return owner?.email || namespace.owner || "";
};
</script>

<style scoped>
.unstyled-link {
  all: unset;
}
.unstyled-link:focus {
  outline: none;
}
</style>
